on: [push, pull_request]
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Test network adapters
        run: yarn e2etest
      # - name: Test REST resources
      #   run: yarn test_rest_resources
